/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "BconomyMarketTracker": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "MakeCandles": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ScrapeMarketValues": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}